/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Objetos.Funciones;
import Objetos.Persona;
import TDatos.Grafo;
import TDatos.Lista;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
//import java.lang.System.Logger;
//import java.lang.System.Logger.Level;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author diego
 */
public class Ventana2 extends javax.swing.JFrame {
    public static Ventana1 v1;
    public static String archivo;
    public static Lista users;

    /**
     * Creates new form Ventana2
     */
    public Ventana2(Ventana1 v1) {
        initComponents();
        this.v1 = v1;
        this.users = new Lista<> ();
        v1.setVisible(false);
        this.setVisible(true);
        this.setLocationRelativeTo(null); //muestra la interfáz en el centro
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        openFile = new javax.swing.JButton();
        saveTxt = new javax.swing.JButton();
        route = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        content = new javax.swing.JTextArea();
        exit = new javax.swing.JButton();
        nextVentana = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        openFile.setBackground(new java.awt.Color(204, 204, 204));
        openFile.setText("Abrir Archivo");
        openFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileActionPerformed(evt);
            }
        });
        jPanel1.add(openFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, 30));

        saveTxt.setBackground(new java.awt.Color(204, 204, 204));
        saveTxt.setText("Guardar ");
        saveTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveTxtActionPerformed(evt);
            }
        });
        jPanel1.add(saveTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 110, 30));

        route.setEditable(false);
        route.setBackground(new java.awt.Color(204, 204, 204));
        route.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                routeActionPerformed(evt);
            }
        });
        jPanel1.add(route, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 310, 30));

        content.setBackground(new java.awt.Color(255, 204, 153));
        content.setColumns(20);
        content.setRows(5);
        jScrollPane1.setViewportView(content);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 370, 220));

        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 40, 20));

        nextVentana.setBackground(new java.awt.Color(204, 255, 204));
        nextVentana.setText("Siguiente -->");
        nextVentana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextVentanaActionPerformed(evt);
            }
        });
        jPanel1.add(nextVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 380, -1, -1));

        jLabel2.setText("Descarga el archivo .txt que deseas usar! Para avanzar, presiona siguiente.");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 390, 70));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fileimagen.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 650, 580));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileActionPerformed
        //JFile Chooser, abrirmos un archivo.
        JFileChooser file = new JFileChooser();
        file.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Archivos de texto", "txt"); //el archivo debe ser ajuro de tipo txt.
        file.setFileFilter(filter); //devuelve un valor entero dependiendo si se elige el boton de abrir o cancelar
        
        int ans = file.showOpenDialog(this);
        if (ans != JFileChooser.CANCEL_OPTION){
            File file_name = file.getSelectedFile();
            if(file_name.getName().equals("")){
               //COMPROBACIONES PARA EVITAR ERRORES MEDIANTE JOPTIONPANE
                JOptionPane.showMessageDialog(this, "Error al abrir el archivo, revise que esté seleccionado el archivo");
            }else{
                    route.setText(file_name.getAbsolutePath());
                try {
                    showContent(file_name.getAbsolutePath());
                } catch (IOException ex) {
                    java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
                }
                }
        }
       
    }//GEN-LAST:event_openFileActionPerformed
    //mostrar contenido del file
    public void showContent(String file_name) throws IOException{
        String line;
        try {
            FileReader f = new FileReader(file_name);
            BufferedReader b = new BufferedReader(f);
            do{
                line = b.readLine();
                content.setText(content.getText()+ line + "\n");
            }while(line != null);
        } catch (FileNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    //METODO GUARDAR LOS ARCHIVOS MEDIANTE WRITETXT
    private void savefile(){
       String info = content.getText();
       try{
            users =v1.f.ListaUsuarios(info);
            v1.f.write_Txt(users, "test\\usuarios.txt");
            v1.grafo.setususarios(users);
            v1.grafo.ImprecionPR();
            JOptionPane.showMessageDialog(null, "Guardado exitoso");
       }catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
       }
    }
    
    private void saveTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveTxtActionPerformed
       this.savefile();
    }//GEN-LAST:event_saveTxtActionPerformed
    
    private void routeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_routeActionPerformed

    }//GEN-LAST:event_routeActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
        v1.setVisible(true);
    }//GEN-LAST:event_exitActionPerformed

    private void nextVentanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextVentanaActionPerformed
       archivo = v1.f.leer_txt();
       if (archivo.isEmpty()){
           JOptionPane.showMessageDialog(null, "ADVERTENCIA! Debe guardar el archivo descargado para continuar."); 
        }else{
           v1.setVisible(true);
           this.setVisible(false);
       } 
       
        
    }//GEN-LAST:event_nextVentanaActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana2(v1).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea content;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextVentana;
    private javax.swing.JButton openFile;
    private javax.swing.JTextField route;
    private javax.swing.JButton saveTxt;
    // End of variables declaration//GEN-END:variables
}
