/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import Objetos.Funciones;
import TDatos.Grafo;

/**
 *
 * @author diego
 */
public class Ventana1 extends javax.swing.JFrame {
    Grafo grafo ;
    Funciones f;
    public static Ventana2 v2;
    public static Ventana3 v3;
    
    

    /**
     * Creates new form Ventana1
     */
    public Ventana1() {
        initComponents();
        this.setVisible(true);
        this.setLocationRelativeTo(null);//muestra la interfáz en el centro
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        exit = new javax.swing.JButton();
        loadFile = new javax.swing.JButton();
        addUser = new javax.swing.JButton();
        design1 = new javax.swing.JLabel();
        deleteUser = new javax.swing.JButton();
        design2 = new javax.swing.JLabel();
        showGraph = new javax.swing.JButton();
        updateRepository = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("--------------------------------------------");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Artifakt Element Heavy", 0, 60)); // NOI18N
        title.setForeground(new java.awt.Color(204, 0, 51));
        title.setText("TU RED SOCIAL");
        jPanel1.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        exit.setForeground(new java.awt.Color(255, 0, 0));
        exit.setText("X");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 40, 20));

        loadFile.setFont(new java.awt.Font("Artifakt Element Book", 1, 14)); // NOI18N
        loadFile.setText("DESCARGAR ARCHIVO");
        loadFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadFileActionPerformed(evt);
            }
        });
        jPanel1.add(loadFile, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, -1, -1));

        addUser.setFont(new java.awt.Font("Artifakt Element Book", 1, 14)); // NOI18N
        addUser.setText("AÑADIR USUARIO");
        addUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addUserActionPerformed(evt);
            }
        });
        jPanel1.add(addUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        design1.setFont(new java.awt.Font("Artifakt Element Black", 1, 100)); // NOI18N
        design1.setForeground(new java.awt.Color(0, 255, 51));
        design1.setText("+");
        jPanel1.add(design1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        deleteUser.setFont(new java.awt.Font("Artifakt Element Book", 1, 14)); // NOI18N
        deleteUser.setText("ELIMINAR USUARIO");
        deleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteUserActionPerformed(evt);
            }
        });
        jPanel1.add(deleteUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        design2.setFont(new java.awt.Font("Artifakt Element Heavy", 1, 100)); // NOI18N
        design2.setForeground(new java.awt.Color(255, 0, 0));
        design2.setText("-");
        jPanel1.add(design2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 140, -1, -1));

        showGraph.setFont(new java.awt.Font("Artifakt Element Book", 1, 14)); // NOI18N
        showGraph.setText("MOSTRAR RED SOCIAL");
        jPanel1.add(showGraph, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, -1, -1));

        updateRepository.setFont(new java.awt.Font("Artifakt Element Book", 1, 14)); // NOI18N
        updateRepository.setText("ACTUALIZAR REPOSITORIO");
        jPanel1.add(updateRepository, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/descarga.jpeg"))); // NOI18N
        background.setText("X");
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 0, 690, 500));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        //SALIR POR COMPLETO DEL PROGRAMA -->
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void loadFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadFileActionPerformed
        Ventana2 v2 = new Ventana2(this);
    }//GEN-LAST:event_loadFileActionPerformed

    private void addUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addUserActionPerformed
        Ventana3 v3 = new Ventana3(this);
    }//GEN-LAST:event_addUserActionPerformed

    private void deleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteUserActionPerformed
        Ventana4 v4 = new Ventana4(this);
    }//GEN-LAST:event_deleteUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addUser;
    private javax.swing.JLabel background;
    private javax.swing.JButton deleteUser;
    private javax.swing.JLabel design1;
    private javax.swing.JLabel design2;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loadFile;
    private javax.swing.JButton showGraph;
    private javax.swing.JLabel title;
    private javax.swing.JButton updateRepository;
    // End of variables declaration//GEN-END:variables
}
